

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install

      - name: Download Cross-platform SonarQube Scanner
        run: |
          curl -o sonar-scanner.zip -L https://url-to-cross-platform-sonar-scanner.zip
          unzip sonar-scanner.zip

      - name: Run SonarQube Analysis
        run: |
          ./sonar-scanner/bin/sonar-scanner

      - name: Test with Jest
        run: |
          npm test


