
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install

      - name: Install Wine (for SonarQube Scanner)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine32

      - name: Download SonarQube Scanner
        run: |
          curl -o sonar-scanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
          unzip sonar-scanner.zip

      - name: Run SonarQube Analysis
        run: |
          wine sonar-scanner-5.0.1.3006-windows/bin/sonar-scanner.bat

      - name: Test with Jest
        run: |
          npm test


